configurationset:
  - configuration:
      name: weather_config
      key: REPLACE_WITH_YOUR_DATA_API_KEY
      stepzen.queryextensionguard: "true"
  - configuration:
      name: mongodb
      apikey: REPLACE_WITH_YOUR_DATA_API_KEY
      appid: REPLACE_WITH_YOUR_DATA_API_APP_ID
