configurationset:
  - configuration:
      name: weather_config
      key: 2110b3198f4545a2963180634242204
      stepzen.queryextensionguard: "true"
  - configuration:
      name: mongodb
      apikey: F3g9mrhFZOzjqBCIV0PkxcT1ua91pcaIbVvfy7QgR6mJXfP9QkmJv8AKiaOV1kpA
      appid: data-bhvwonr
